= Semaphore

:imagesdir: ../images

Semaphore（信号量）是用来控制同时访问特定资源的线程数量，它通过协调各个线程，以保证合理的使用公共资源。很多年以来，我都觉得从字面上很难理解Semaphore所表达的含义，只能把它比作是控制流量的红绿灯，比如XX马路要限制流量，只允许同时有一百辆车在这条路上行使，其他的都必须在路口等待，所以前一百辆车会看到绿灯，可以开进这条马路，后面的车会看到红灯，不能驶入XX马路，但是如果前一百辆中有五辆车已经离开了XX马路，那么后面就允许有5辆车驶入马路，这个例子里说的车就是线程，驶入马路就表示线程在执行，离开马路就表示线程执行完成，看见红灯就表示线程被阻塞，不能执行。

Semaphore可以用于做流量控制，特别公用资源有限的应用场景，比如数据库连接。假如有一个需求，要读取几万个文件的数据，因为都是IO密集型任务，我们可以启动几十个线程并发的读取，但是如果读到内存后，还需要存储到数据库中，而数据库的连接数只有10个，这时我们必须控制只有十个线程同时获取数据库连接保存数据，否则会报错无法获取数据库连接。这个时候，我们就可以使用Semaphore来做流控，代码如下:

[source,java]
----
public class SemaphoreTest {

	private static final int THREAD_COUNT = 30;

	private static ExecutorService threadPool = Executors
			.newFixedThreadPool(THREAD_COUNT);

	private static Semaphore s = new Semaphore(10);

	public static void main(String[] args) {
		for (int i = 0; i < THREAD_COUNT; i++) {
			threadPool.execute(new Runnable() {
				@Override
				public void run() {
					try {
						s.acquire();
						System.out.println("save data");
						s.release();
					} catch (InterruptedException e) {
					}
				}
			});
		}

		threadPool.shutdown();
	}
}
----

在代码中，虽然有30个线程在执行，但是只允许10个并发的执行。Semaphore的构造方法Semaphore(int permits) 接受一个整型的数字，表示可用的许可证数量。Semaphore(10)表示允许10个线程获取许可证，也就是最大并发数是10。Semaphore的用法也很简单，首先线程使用Semaphore的acquire()获取一个许可证，使用完之后调用release()归还许可证。还可以用tryAcquire()方法尝试获取许可证。


==  其他方法

. int availablePermits() ：返回此信号量中当前可用的许可证数。
. int getQueueLength()：返回正在等待获取许可证的线程数。
. boolean hasQueuedThreads() ：是否有线程正在等待获取许可证。
. void reducePermits(int reduction) ：减少reduction个许可证。是个protected方法。
. Collection getQueuedThreads() ：返回所有等待获取许可证的线程集合。是个protected方法。


==  源码分析

我们先来看acquire方法:
[source,java]
----
    public void acquire() throws InterruptedException {
        sync.acquireSharedInterruptibly(1);
    }
----

在Semaphore内部,Sync类型实现了AQS类,FairSync和NonfairSync继承了Sync.上面的sync就是FairSync或NonfairSync的实例

下面的代码讲述以NonfairSync为例:
[source,java]
----
        final int nonfairTryAcquireShared(int acquires) {
            for (;;) {
                int available = getState(); <1>
                int remaining = available - acquires; <2>
                if (remaining < 0 ||
                    compareAndSetState(available, remaining)) <3>
                    return remaining;
            }
        }
----

<1> 获取现在还有几个线程被允许执行
<2> 减去acquires值在这里为1,代表当前线程进入,尝试获取锁
<3> 如果remaining大于0,代表还有名额可以进入,然后设置状态,设置状态成功后获取许可


我们再来看release方法:

[source,java]
----
    public void release() {
        sync.releaseShared(1);
    } 
    
    protected final boolean tryReleaseShared(int releases) {
            for (;;) {
                int current = getState();
                int next = current + releases;
                if (next < current) // overflow
                    throw new Error("Maximum permit count exceeded");
                if (compareAndSetState(current, next))
                    return true;
            }
    }
----

这个代码就是一个相反的过程,说白了,整个过程跟生产者消费者模型有点相似.里面使用了AQS共享锁的方法