= spring-cloud-task-App-Starters

== 1.Spring Cloud Task Starters

=== 1.1概述

Spring Cloud Task Application Starters为您提供了可以独立运行或使用Spring Cloud Data Flow运行的预定义Spring Cloud Task应用程序。 您还可以使用 Starters作为创建自己的应用程序的基础。你可以原样运行这些starters程序,或者按需修改.

=== 1.2 starte和预置应用

作为Spring Cloud Task Application Starters的用户，您可以访问两种类型的工件:

. Starters是包含具有特定角色的Spring Cloud Task应用程序的完整配置的库（例如，通过sql查询将数据从JDBC存储库迁移到hdfs上的文件）。 Starters不是可执行应用程序，并且旨在包含在其他Spring Boot应用程序中。

. 预构建的应用程序是包含starter的Spring Boot应用程序。 预构建的应用程序是uberjars，包含独立运行所需的最少代码。

==== 1.2.1 Maven和docker

Starters可以通过maven的形式获取,例如:
[source,xml]
----
<dependency>
  <group>org.springframework.cloud.task.app</group>
  <artifactId>spring-cloud-starter-task-timestamp</artifactId>
  <version>1.0.0.BUILD-SNAPSHOT</version>
</dependency>
----

预建应用程序也可用作Maven工件。不鼓励将它们直接用作依赖项，因为应该使用Starters。其依赖是:
	org.springframework.cloud.task.app:timestamp-task:1.0.0.BUILD-SNAPSHOT

*docker*

可以通过下面的方式获取
	docker pull springcloudtask/timestamp-task

==== 1.2.2 构建artifacts

您还可以自己构建项目并生成工件（包括预构建的应用程序）。如果要在本地部署工件（例如添加新的starter），这将非常有用。

首先，您需要生成预构建的应用程序。 有一个maven配置文件可以做到这一点。
	./mvnw clean install -PgenerateApps

然后构建应用
----
cd apps

mvn clean install
----

每个生成的应用由下面几部分组成

. pom.xml
. 包含应用程序main方法并导入预定义配置的类
. 生成集成测试代码，用于运行组件。

=== 1.3 创建自定义工件

有的时候,预置的starter并不能满足我们生产的需要,这个时候我们可以自己开发或者扩展已有的starter.有两种方案:
. 创建spring cloud task应用
. 使用starters创建自定义的版本

如果要将自定义应用程序添加到解决方案中，只需创建一个新的Spring Cloud Task项目，并以与Spring Cloud Task Application Starters相同的方式独立运行或通过Spring Cloud Data Flow运行。 Spring Cloud Task入门指南中介绍了该过程。

您还可以重用Spring Cloud Task Application Starters提供的启动器来创建自定义组件，从而丰富应用程序的行为。例如，您可以向jdbc hdfs任务添加特殊行为，以便在迁移数据后执行一些后处理。 提醒一下，这包括：

**添加starter到项目中**
[source,xml]
----
<dependencies>
  <!- other dependencies -->
  <dependencies>
    <dependency>
      <groupId>org.springframework.cloud.task.app</groupId>
      <artifactId>spring-cloud-starter-task-timestamp</artifactId>
    </dependency>
</dependencies>
----

**添加主类并导入启动器配置**
[source,java]
----
package org.springframework.cloud.task.app.timestamp;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Import;


@SpringBootApplication
@Import(org.springframework.cloud.task.app.timestamp.TimestampTaskConfiguration.class)
public class TimestampTaskApplication {

        public static void main(String[] args) {
                SpringApplication.run(TimestampTaskApplication.class, args);
        }
}
----

完成此操作后，您只需为应用程序的其他功能添加其他配置即可。

=== 1.4 开发工件

在本节中，我们将解释如何开发自定义任务应用程序，然后使用spring cloud task app starter infrastructure提供的现有工具为其生成maven和docker工件。出于解释目的，我们假设我们正在为名为foobar的技术创建新的任务应用程序。

1.从github上下载项目https://github.com/spring-cloud-task-app-starters/timestamp[模板],删除timestamp maven模块
2.创建新的maven模块spring-cloud-starter-task-foobar
3.在pom.xml中添加:
[source,xml]
----
    <parent>
        <groupId>org.springframework.cloud.task.app</groupId>
        <artifactId>timestamp-task-app-starters-build</artifactId>
        <version>2.1.0.BUILD-SNAPSHOT</version>
    </parent>
----

4.在模块下创建@Configuration类,命名为FoobarTaskConfiguration(因为这是稍后应用程序生成所使用的默认约定)。
5.在模块下的pom文件中,添加:
[source,xml]
----
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-app-starter-doc-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.springframework.cloud.stream.app.plugin</groupId>
                <artifactId>spring-cloud-stream-app-maven-plugin</artifactId>
                <configuration>
                    <generatedProjectHome>${session.executionRootDirectory}/apps</generatedProjectHome>
                    <generatedProjectVersion>${project.version}</generatedProjectVersion>
                    <bom>
                        <name>scs-bom</name>
                        <groupId>org.springframework.cloud.task.app</groupId>
                        <artifactId>timestamp-task-app-dependencies</artifactId>
                        <version>${project.version}</version>
                    </bom>
                    <generatedApps>
                        <timestamp-task />
                    </generatedApps>
                </configuration>
            </plugin>
        </plugins>
    </build>
----

====

NOTE: 之前配置的FoobarTaskConfiguration是根据约定在指定的包下面的,如果自定义,可以这样指定:

[source,xml]
----
<foobar-task>
    <autoConfigClass>foo.bar.SpecialFooBarTaskConfiguration.class</autoConfigClass>
</foobar-task>
----
====

6.生成app: `mvn clean install -PgenerateApps`,这将在项目根目录中名为apps的目录中生成foobar任务应用程序。 如果要更改生成应用程序的位置，例如/tmp/task-apps，您可以在插件的配置部分中执行此操作:
[source,xml]
----
<configuration>
    ...
    <generatedProjectHome>/tmp/task-apps</generatedProjectHome>
    ...
</configuration
----
7.此时会生产项目的源码信息,然后你可以导入到开发工具中,开发具体的模块.

