= spring-cloud-OpenFeign

Feign是一个声明性的Web服务客户端。它使编写Web服务客户端变得更容易。要使用Feign，请创建一个接口并对其进行注释。它具有可插入的注释支持，包括Feign注释和JAX-RS注释。 Feign还支持可插拔编码器和解码器。Spring Cloud增加了对Spring MVC注释的支持，并使用了Spring Web中默认使用的相同HttpMessageConverters。 Spring Cloud集成了Ribbon和Eureka，在使用Feign时提供负载均衡的http客户端。

== 1.引入依赖
. group:org.springframework.cloud
. artifact:spring-cloud-starter-openfeign

[source,java]
----
@SpringBootApplication
@EnableFeignClients
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

}
----

.客户端调用
[source,java]
----
@FeignClient("stores")
public interface StoreClient {
    @RequestMapping(method = RequestMethod.GET, value = "/stores")
    List<Store> getStores();

    @RequestMapping(method = RequestMethod.POST, value = "/stores/{storeId}", consumes = "application/json")
    Store update(@PathVariable("storeId") Long storeId, Store store);
}
----

@FeignClient的值是服务的名称,主要用来负载均衡.当然也可以用url属性来指定具体的地址.该接口在上下文中注册的bean名称是完全限定名称,你可以使用qualifier属性来指定别名.

上面的Ribbon客户端将要发现“strore”服务的物理地址。如果您的应用程序是Eureka客户端，那么它将解析Eureka服务注册表中的服务。如果您不想使用Eureka，则只需在外部配置中配置服务器列表即可.

== 2.修改默认配置

feign的核心概念是命名的客户端,每个客户端是一组链接远程服务的组件,开发人员通过@FeignClient注解指定这组组件的名称.

Spring Cloud使用FeignClientsConfiguration按需为每个命名客户端创建一个新的集合作为ApplicationContext.这包含（除其他外）feign.Decoder，feign.Encoder和feign.Contract。 可以使用@FeignClient批注的contextId属性覆盖该集合的名称。

Spring Cloud允许您通过使用@FeignClient声明其他配置（在FeignClientsConfiguration之上）来完全控制feign客户端。 例：
[source,java]
----
@FeignClient(name = "stores", configuration = FooConfiguration.class)
public interface StoreClient {
    //..
}
----
在这种情况下，客户端由FeignClientsConfiguration中已有的组件以及FooConfiguration中的默认组件组成（后者将覆盖前者）。

NOTE: FooConfiguration类不需要被@Configuration标注.注意不要配置在@ComponentScan指定的包范围,否则会成为全局默认配置.

NOTE:serviceId属性已经被name属性取代

NOTE:除了更改ApplicationContext集合的名称之外，使用@FeignClient批注的contextId属性，它还会覆盖客户端名称的别名，并将其用作为该客户端创建的配置bean名称的一部分。

NOTE:以前，使用url属性不需要name属性。 现在需要使用name。

name和url属性支持占位符:
[source,java]
----
@FeignClient(name = "${feign.name}", url = "${feign.url}")
public interface StoreClient {
    //..
}
----
Spring Cloud Netflix默认为feign（BeanType beanName：ClassName）提供以下bean：
. Decoder feignDecoder: ResponseEntityDecoder (which wraps a SpringDecoder)
. Encoder feignEncoder: SpringEncoder
. Logger feignLogger: Slf4jLogger
. Contract feignContract: SpringMvcContract
. Feign.Builder feignBuilder: HystrixFeign.Builder
. Client feignClient: 如果启用Ribbon是LoadBalancerFeignClient,否则是默认客户端

可以通过将feign.okhttp.enabled或feign.httpclient.enabled分别设置为true并将依赖放在类路径上来使用OkHttpClient和ApacheHttpClient假装客户端。 您可以在使用OK时使用OkHttpClient或者Apache是使用ClosableHttpClient的bean来自定义所使用的HTTP客户端。

Spring Cloud Netflix默认情况下不为feign提供以下bean，但仍然从应用程序上下文中查找这些类型的bean以创建feign客户端：

. Logger.Level
. Retryer
. ErrorDecoder
. Request.Options
. Collection<RequestInterceptor>
. SetterFactory
创建其中一种类型的bean并将其放在@FeignClient配置中（例如上面的FooConfiguration）允许您覆盖所描述的每个bean。 例：
[source,java]
----
@Configuration
public class FooConfiguration {
    @Bean
    public Contract feignContract() {
        return new feign.Contract.Default();
    }

    @Bean
    public BasicAuthRequestInterceptor basicAuthRequestInterceptor() {
        return new BasicAuthRequestInterceptor("user", "password");
    }
}
----
这将使用feign.Contract.Default替换SpringMvcContract，并将RequestInterceptor添加到RequestInterceptor的集合中。

@FeignClient也可以使用配置属性进行配置。
[source,yml]
----
feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        errorDecoder: com.example.SimpleErrorDecoder
        retryer: com.example.SimpleRetryer
        requestInterceptors:
          - com.example.FooRequestInterceptor
          - com.example.BarRequestInterceptor
        decode404: false
        encoder: com.example.SimpleEncoder
        decoder: com.example.SimpleDecoder
        contract: com.example.SimpleContract
----
可以以与上述类似的方式在@EnableFeignClients属性defaultConfiguration中指定默认配置。 不同之处在于此配置将适用于所有Fiegn 客户端。

如果您更喜欢使用配置属性来配置所有@FeignClient，则可以使用default名称创建配置属性。
[source,yml]
----
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
----

如果我们同时创建@Configuration bean和配置属性，配置属性将获胜。它将覆盖@Configuration值。 但是，如果要将优先级更改为@Configuration，则可以将feign.client.default-to-properties更改为false。

如果需要在RequestInterceptor中使用ThreadLocal绑定变量，则需要将Hystrix的线程隔离策略设置为“SEMAPHORE”或在Feign中禁用Hystrix。
[source,yml]
----
# To disable Hystrix in Feign
feign:
  hystrix:
    enabled: false

# To set thread isolation to SEMAPHORE
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
----

如果我们想要创建具有相同名称或URL的多个feign客户端，以便它们指向同一服务器但每个都具有不同的自定义配置，那么我们必须使用@FeClClient的contextId属性以避免这些配置的名称冲突。
[source,java]
----
@FeignClient(contextId = "fooClient", name = "stores", configuration = FooConfiguration.class)
public interface FooClient {
    //..
}
@FeignClient(contextId = "barClient", name = "stores", configuration = BarConfiguration.class)
public interface BarClient {
    //..
}
----

== 3.自定义feign客户端

在某些情况下，可能需要以使用上述方法无法实现符合自己需求的Feign客户端。在这种情况下，您可以使用Feign Builder API创建客户端。 下面是一个示例，它创建两个具有相同接口的Feign客户端，但使用单独的请求拦截器配置每个客户端。
[source,java]
----
@Import(FeignClientsConfiguration.class) <1>
class FooController {

	private FooClient fooClient;

	private FooClient adminClient;

    	@Autowired
	public FooController(Decoder decoder, Encoder encoder, Client client, Contract contract) {<3>
		this.fooClient = Feign.builder().client(client)
				.encoder(encoder)
				.decoder(decoder)
				.contract(contract)
				.requestInterceptor(new BasicAuthRequestInterceptor("user", "user"))
				.target(FooClient.class, "http://PROD-SVC"); <2>

		this.adminClient = Feign.builder().client(client)
				.encoder(encoder)
				.decoder(decoder)
				.contract(contract)
				.requestInterceptor(new BasicAuthRequestInterceptor("admin", "admin"))
				.target(FooClient.class, "http://PROD-SVC");
    }
}
----

<1> FeignClientsConfiguration.class是Spring Cloud Netflix提供的默认配置。
<2> PROD-SVC是服务名称
<3> Contract定义接口上哪些注解和值是有效的,上面注入的Contract支持Spring mvc注解,取代feign的默认注解

== 4.Hystrix支持
如果Hystrix在类路径并且feign.hystrix.enabled=true,feign会包装方法成断路器模式.返回com.netflix.hystrix.HystrixCommand也可用。 这允许您使用反应模式（通过调用.toObservable（）或.observe（）或异步使用（通过调用.queue（））。

要在每个客户端的基础上禁用Hystrix支持，请创建一个带有“prototype”范围的Feign.Builder，例如：
[source,java]
----
@Configuration
public class FooConfiguration {
    	@Bean
	@Scope("prototype")
	public Feign.Builder feignBuilder() {
		return Feign.builder();
	}
}
----

NOTE: 在Spring Cloud Dalston发布之前，如果Hystrix在类路径上，Feign会默认将所有方法包装在断路器中。 Spring Cloud Dalston中更改了此默认行为，转而采用了选择加入方法。


== 5.Hystrix Fallback

Hystrix支持回退的概念：当断路器打开或出现错误时执行的默认代码路径。要为给定的@FeignClient启用回退，请将fallback属性设置为实现回退的类名。您还需要将实现声明为Spring bean。
[source,java]
----
@FeignClient(name = "hello", fallback = HystrixClientFallback.class)
protected interface HystrixClient {
    @RequestMapping(method = RequestMethod.GET, value = "/hello")
    Hello iFailSometimes();
}

static class HystrixClientFallback implements HystrixClient {
    @Override
    public Hello iFailSometimes() {
        return new Hello("fallback");
    }
}
----

如果需要访问产生回退触发器的原因，可以使用@FeignClient中的fallbackFactory属性。
[source,java]
----
@FeignClient(name = "hello", fallbackFactory = HystrixClientFallbackFactory.class)
protected interface HystrixClient {
	@RequestMapping(method = RequestMethod.GET, value = "/hello")
	Hello iFailSometimes();
}

@Component
static class HystrixClientFallbackFactory implements FallbackFactory<HystrixClient> {
	@Override
	public HystrixClient create(Throwable cause) {
		return new HystrixClient() {
			@Override
			public Hello iFailSometimes() {
				return new Hello("fallback; reason was: " + cause.getMessage());
			}
		};
	}
}
----

NOTE: 在Feign中实现回退以及Hystrix回退如何工作存在限制。 返回com.netflix.hystrix.HystrixCommand和rx.Observable的方法目前不支持回退。

== 6.Feign and @Primary

使用Feign with Hystrix后备时，ApplicationContext中有多个相同类型的bean。 这将导致@Autowired无法工作，因为没有一个确切的bean或一个标记为primary的bean。为了解决这个问题，Spring Cloud Netflix将所有Feign实例标记为@Primary，因此Spring Framework将知道要注入哪个bean。 在某些情况下，这可能并不理想。要关闭此行为，请将@FeignClient的主要属性设置为false。
[source,java]
----
@FeignClient(name = "hello", primary = false)
public interface HelloClient {
	// methods here
}
----

== 7.对继承的支持

Feign通过单继承接口支持样板apis。 这允许将常见操作分组为方便的基本接口。

.UserService.java
[source,java]
----
public interface UserService {

    @RequestMapping(method = RequestMethod.GET, value ="/users/{id}")
    User getUser(@PathVariable("id") long id);
}
----

.UserResource.java
[source,java]
----
@RestController
public class UserResource implements UserService {

}
----

.UserClient.java
[source,java]
----
package project.user;

@FeignClient("users")
public interface UserClient extends UserService {

}
----

NOTE: 通常不建议在服务器和客户端之间共享接口。它引入了紧耦合，并且实际上也不能以其当前形式使用Spring MVC（方法参数映射不会被继承）。

== 8.请求和响应压缩

您可以考虑为您的Feign请求启用请求或响应GZIP压缩。您可以通过启用以下属性之一来执行此操作：
----
feign.compression.request.enabled=true
feign.compression.response.enabled=true
----

feign请求压缩为您提供类似于您为Web服务器设置的设置：
----
feign.compression.request.enabled=true
feign.compression.request.mime-types=text/xml,application/xml,application/json
feign.compression.request.min-request-size=2048
----

通过这些属性，您可以选择压缩介质类型和最小请求阈值长度。

== 9. Feign logging

为每个创建的Feign客户端创建一个记录器。默认情况下，记录器的名称是用于创建Feign客户端的接口的完整类名。 Feign日志记录仅响应DEBUG级别。
----
logging.level.project.user.UserClient: DEBUG
----

您可以为每个客户端配置的Logger.Level对象告诉Feign要记录多少。 选择是：

. NONE:不记录(DEFAULT).
. BASIC:仅记录请求方法和URL以及响应状态代码和执行时间。
. HEADERS:记录基本信息以及请求和响应标头。
. FULL:记录请求和响应的标题，正文和元数据。

例如，以下内容将Logger.Level设置为FULL：
[source,java]
----
@Configuration
public class FooConfiguration {
    @Bean
    Logger.Level feignLoggerLevel() {
        return Logger.Level.FULL;
    }
}
----

== 10.@QueryMap支持

OpenFeign @QueryMap注释为POJO提供了支持，可用作GET参数映射。不幸的是，默认的OpenFeign QueryMap注释与Spring不兼容，因为它缺少值属性。

Spring Cloud OpenFeign提供等效的@SpringQueryMap注释，用于将POJO或Map类型指定为请求参数.

例如,Params类定义了param1和param2参数:
[source,java]
----
// Params.java
public class Params {
    private String param1;
    private String param2;

    // [Getters and setters omitted for brevity]
}
----

以下feign客户端使用@SpringQueryMap注释使用Params类：
[source,java]
----
@FeignClient("demo")
public class DemoTemplate {

    @GetMapping(path = "/demo")
    String demoEndpoint(@SpringQueryMap Params params);
}
----