= spring security
:toc: left
:icons: font
:sectanchors: 
:toclevels: 4
:source-highlighter: pygments
:pygments-style: manni
:source-linenums-option: 



== 概述

=== DelegatingFilterProxy

我们先来看看DelegatingFilterProxy的doc解释：

____

代理一个标准的Servlet过滤器，委托给一个实现了Filter接口的Spring管理的bean。
____

实际的业务逻辑是交给名为springSecurityFilterChain(可自定义)的bean处理的。该bean的类型是org.springframework.security.web.FilterChainProxy。他维护了一个有顺序的过滤器链来处理用户的请求。


=== web认证过程

. 您访问主页，然后点击链接。
. 请求发送到服务器，并且服务器确定您正在请求受保护的资源。
. 由于您目前没有通过身份验证，因此服务器会发回一个响应，指出您必须进行身份验证。 响应可能是HTTP响应代码，也可能是重定向到特定网页。
. 根据身份验证机制，您的浏览器将重定向到特定网页，以便填写表单，或者浏览器以某种方式检索您的身份（通过BASIC身份验证对话框，Cookie，X.509证书等））。
. 浏览器会发回一个请求给服务器。 这一个HTTP POST请求，其中包含您填写的表单的内容或包含您的验证细节的HTTP标头。
. 接下来，服务器将决定提交的凭证是否有效。 如果它们有效，下一步就会发生。 如果它们无效，通常你的浏览器会被要求重试（所以你回到上面的第二步）。
. 身份验证通过后，开始进行权限验证。如果您有足够的访问权限，请求将会成功。 否则，您将收到一个HTTP错误代码403，意思是禁止访问。

Spring Security提供了多个类处理上述大多数步骤。但主要的参与者（按顺序）是ExceptionTranslationFilter，AuthenticationEntryPoint和一个“认证机制”（负责调用uthenticationManager）。


<<ExceptionTranslationFilter,ExceptionTranslationFilter>>是一个Spring Security过滤器，负责检测抛出的任何Spring安全异常。例如<<AbstractSecurityInterceptor,AbstractSecurityInterceptor>>（授权服务的主要提供者）抛出的异常,他可能会返回错误代码403（如果主体已经过身份验证，但是没有足够的访问权限 - 按照上述步骤7），或者启动AuthenticationEntryPoint（如果主体尚未经过身份验证，按照上述步骤3）。

如果用户请求安全的HTTP资源但未通过身份验证，则将调用AuthenticationEntryPoint。一个合适的AuthenticationException或者AccessDeniedException将会被安全拦截器抛出，触发入口点的方法。 这可以向用户提供适当的响应，以便进行认证。 一般使用的是LoginUrlAuthenticationEntryPoint，它将请求重定向到不同的URL（通常是登录页面）。 


一旦您的浏览器提交了您的身份验证凭证（无论是作为HTTP表单发布还是HTTP标头），服务器上都需要有一些“收集”这些身份验证信息的东西。在Spring Security中，我们为从用户代理（通常是Web浏览器）收集验证信息的功能提供了一个特殊的名称，称之为“验证机制”。 示例是基于表单的登录和基本身份验证。 一旦从用户代理收集了认证详细信息，就会构建一个认证“请求”对象，然后将其呈现给AuthenticationManager。认证机制接收到完全填充的认证对象后，认为请求有效，将认证放入SecurityContextHolder，并导致原始请求重试（上面的第七步）。 另一方面，如果AuthenticationManager拒绝了请求，认证机制将要求用户代理重试（上面的第二步）。


=== 安全对象

Spring Security使用这个术语来指代可以有安全性的任何对象（例如授权决定）。最常见的例子是方法调用和Web请求。每个支持的安全对象类型都有自己的拦截器类，它是AbstractSecurityInterceptor的一个子类。 重要的是，在AbstractSecurityInterceptor被调用的时候，如果委托人已被认证，SecurityContextHolder将包含一个有效的认证。

AbstractSecurityInterceptor[[AbstractSecurityInterceptor]]为处理安全对象请求提供了一致的工作流程，通常为：

. 查找与当前请求关联的“配置属性”

. 将安全对象，Authentication和配置属性提交给AccessDecisionManager以作出授权决定

. 在调用之前，可以选择更改Authentication

. 允许安全对象调用继续（假设访问被授予）

. 一旦调用返回，调用AfterInvocationManager（如果已配置）。 如果调用引发异常，则不会调用AfterInvocationManager。

=== 关键的过滤器

==== 过滤器的顺序

过滤器在链中定义的顺序非常重要。 无论您实际使用哪些过滤器，顺序应如下所示：

. ChannelProcessingFilter，因为它可能需要重定向到不同的协议
. SecurityContextPersistenceFilter，因此SecurityContext可以在Web请求开始时的SecurityContextHolder中设置，并且可以在Web请求结束时将SecurityContext的任何更改复制到HttpSession中（准备好用于下一个Web请求）
. ConcurrentSessionFilter，因为它使用SecurityContextHolder功能并需要更新SessionRegistry以反映来自主体的持续请求
. 身份验证处理机制 - UsernamePasswordAuthenticationFilter，CasAuthenticationFilter，BasicAuthenticationFilter等 - 以便可以修改SecurityContextHolder以包含有效的身份验证请求令牌
. SecurityContextHolderAwareRequestFilter，如果你正在使用它来安装Spring Security HttpServletRequestWrapper到你的servlet容器
. JaasApiIntegrationFilter，如果一个JaasAuthenticationToken在SecurityContextHolder中，它将把FilterChain作为JaasAuthenticationToken中的Subject
. RememberMeAuthenticationFilter，这样如果没有更早的认证处理机制更新SecurityContextHolder，并且请求提供了一个允许记住我服务的cookie，那么一个合适的记忆认证对象将会放在那里
. AnonymousAuthenticationFilter，这样如果没有更早的认证处理机制更新SecurityContextHolder，那么匿名认证对象将会放在那里
. ExceptionTranslationFilter，捕获任何Spring Security异常，以便返回HTTP错误响应或者可以启动相应的AuthenticationEntryPoint
. FilterSecurityInterceptor，用于保护Web URI并在访问被拒绝时引发异常

==== FilterSecurityInterceptor

FilterSecurityInterceptor负责URL鉴权。 它需要引用AuthenticationManager和AccessDecisionManager。 它还提供了适用于不同HTTP URL请求的配置属性。 
[source,xml]
----
<bean id="filterSecurityInterceptor" class="org.springframework.security.web.access.intercept.FilterSecurityInterceptor">
	<property name="authenticationManager" ref="authenticationManager"/>
	<property name="accessDecisionManager" ref="accessDecisionManager"/>
	<property name="securityMetadataSource">
			<security:filter-security-metadata-source>
				<security:intercept-url pattern="/secure/super/**" access="ROLE_WE_DONT_HAVE"/>
				<security:intercept-url pattern="/secure/**" access="ROLE_SUPERVISOR,ROLE_TELLER"/>
			</security:filter-security-metadata-source>
	</property>
</bean>
----
[[ExceptionTranslationFilter]]
==== ExceptionTranslationFilter
ExceptionTranslationFilter位于FilterSecurityInterceptor之前。 它本身并不执行任何实际的安全性实施，但处理安全拦截器引发的异常并提供合适的HTTP响应。
[source,xml]
----
<bean id="exceptionTranslationFilter" class="org.springframework.security.web.access.ExceptionTranslationFilter">
	<property name="authenticationEntryPoint" ref="authenticationEntryPoint"/>
	<property name="accessDeniedHandler" ref="accessDeniedHandler"/>
</bean>

<bean id="authenticationEntryPoint" class="org.springframework.security.web.authentication.LoginUrlAuthenticationEntryPoint">
	<property name="loginFormUrl" value="/login.jsp"/>
</bean>

<bean id="accessDeniedHandler" class="org.springframework.security.web.access.AccessDeniedHandlerImpl">
	<property name="errorPage" value="/accessDenied.htm"/>
</bean>
----

ExceptionTranslationFilter的另一个职责是在调用AuthenticationEntryPoint之前保存当前请求，这允许在用户通过身份验证后恢复请求。一个典型的例子是用户使用表单登录，然后通过默认的SavedRequestAwareAuthenticationSuccessHandler重定向到原始URL。RequestCache存储和检索HttpServletRequest实例。默认情况下使用HttpSessionRequestCache，它将请求存储在HttpSession中。当用户被重定向到原始URL时，RequestCacheFilter恢复缓存中保存的请求。

==== SecurityContextPersistenceFilter

它负责存储HTTP请求之间的SecurityContext内容，并在请求完成时清除SecurityContextHolder。清除存储上下文的ThreadLocal非常重要，因为可能会将某个线程替换到servlet容器的线程池中，并为特定的用户提供安全上下文, 此线程可能会在稍后阶段使用，并使用错误的凭据执行操作。

默认实现是HttpSessionSecurityContextRepository，它将安全上下文存储为HttpSession属性。该实现的最重要的配置参数是allowSessionCreation属性，默认为true，如果类需要存储经过身份验证的用户的安全上下文，则允许该类创建会话（它不会创建一个，除非已进行身份验证或安全上下文的内容发生改变）。 如果您不想创建会话，则可以将此属性设置为false：
[source,xml]
----
<bean id="securityContextPersistenceFilter"
	class="org.springframework.security.web.context.SecurityContextPersistenceFilter">
	<property name='securityContextRepository'>
		<bean class='org.springframework.security.web.context.HttpSessionSecurityContextRepository'>
			<property name='allowSessionCreation' value='false' />
		</bean>
	</property>
</bean>
----

或者，您可以提供一个NullSecurityContextRepository实例，一个空对象实现，它将阻止安全上下文被存储，即使在请求期间已经创建了一个会话。

==== UsernamePasswordAuthenticationFilter

现在我们已经看到Spring Security web配置中总是存在三种主要过滤器。 这些也是由名称空间<http>元素自动创建的三个，不能用替代选项替代。现在唯一缺少的是实际的身份验证机制，这将允许用户进行身份验证。 这个过滤器是最常用的认证过滤器，也是用户经常自定义配置的地方。 它还提供名称空间中<form-login>元素使用的实现。 配置它需要三个步骤。

* 就像我们上面所做的一样，使用登录页面的URL配置LoginUrlAuthenticationEntryPoint，并将其设置在ExceptionTranslationFilter上。
* 实现登录页面（使用JSP或MVC控制器）
* 在容器中配置UsernamePasswordAuthenticationFilter的实例

登录表单只包含用户名和密码，并路由到过滤器监控的URL（默认情况下为/ login）。 基本的过滤器配置如下所示：
[source,xml]
----
<bean id="authenticationFilter" class=
"org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter">
	<property name="authenticationManager" ref="authenticationManager"/>
</bean>
----

过滤器调用配置的AuthenticationManager来处理每个认证请求。 验证成功或验证失败后的目标分别由AuthenticationSuccessHandler和AuthenticationFailureHandler策略接口控制。 提供了一些标准实现，例如SimpleUrlAuthenticationSuccessHandler，SavedRequestAwareAuthenticationSuccessHandler，SimpleUrlAuthenticationFailureHandler，ExceptionMappingAuthenticationFailureHandler和DelegatingAuthenticationFailureHandler。 查看这些类的Javadoc以及AbstractAuthenticationProcessingFilter以了解它们如何工作以及支持的功能。

如果认证成功，则生成的认证对象将被放置到SecurityContextHolder中。 然后将调用配置的AuthenticationSuccessHandler来重定向或将用户转发到适当的目标。 默认情况下，使用SavedRequestAwareAuthenticationSuccessHandler，这意味着用户在被要求登录之前将被重定向到他们请求的原始目的地。

== 快速入门

=== 基于Spring MVC配置

*1.添加依赖*
[source,xml]
----
<dependency>
	<groupId>org.springframework.security</groupId>
	<artifactId>spring-security-web</artifactId>
	<version>5.0.3.RELEASE</version>
</dependency>
<dependency>
	<groupId>org.springframework.security</groupId>
	<artifactId>spring-security-config</artifactId>
	<version>5.0.3.RELEASE</version>
</dependency>
----

*2.Spring MVC配置*
[source,java]
----
@Configuration
@EnableWebMvc
@ComponentScan
public class WebMvcConfig implements WebMvcConfigurer {

}
----

*3.Spring security配置*

[source,java]
----
@EnableWebSecurity
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

    @Autowired
    private DataSource dataSource;

    @Bean
    public UserDetailsService userDetailsService() {
     
    	InMemoryUserDetailsManager manager = new InMemoryUserDetailsManager();
    	UserDetails user=User.withDefaultPasswordEncoder()
    		.username("user").password("password").roles("USER").build()
        manager.createUser(user);
        return manager;
    }
}
----

该配置会创建一个名为springSecurityFilterChain的Servlet过滤器，它负责应用程序中的所有安全性（保护应用程序URL，验证提交的用户名和密码，重定向到登录表单等）

.上面的配置到底做了哪些工作？
****
上面的配置到底做了哪些工作？

	* 要求对应用程序中的每个URL进行认证
    * 为您生成一个登录表单
    * 允许具有用户名为user和密码为password的用户使用基于表单的身份验证进行身份验证
    * 允许用户注销
    * CSRF攻击预防
	* 会话固定保护
	* 安全头集成
		** 用于安全请求的HTTP严格传输安全性
		** X-Content-Type-Options集成
		** 高速缓存控制（稍后可由应用程序覆盖，以允许缓存静态资源）
		** X-XSS-Protection集成
		** X-Frame-Options集成有助于防止点击劫持
	* 与以下Servlet API方法集成
		** HttpServletRequest#getRemoteUser()
		** HttpServletRequest#getUserPrincipal()
		** HttpServletRequest#isUserInRole(java.lang.String)
		** HttpServletRequest#login(java.lang.String, java.lang.String)
		** HttpServletRequest#logout()
****

*4.注册springSecurityFilterChain bean*
[source,java]
----
import org.springframework.security.web.context.*;

public class SecurityWebApplicationInitializer
	extends AbstractSecurityWebApplicationInitializer {

}
----

步骤三注册了名为springSecurityFilterChain的过滤器，上述的过程就是绑定过滤器和spring容器springSecurityFilterChain bean的关系。


IMPORTANT: AbstractAnnotationConfigDispatcherServletInitializer注册DispatcherServlet。springSecurityFilterChain是filter,同ispatcherServlet时Spring mvc的入口一样，springSecurityFilterChain是spring security的入口。

*5.注册mvc和security配置文件*

[source,java]
----
public class MyWebApplicationInitializer extends AbstractAnnotationConfigDispatcherServletInitializer {


    protected Class<?>[] getRootConfigClasses() {
        return new Class[]{WebMvcConfig.class, WebSecurityConfig.class};
    }

    protected Class<?>[] getServletConfigClasses() {
        return new Class[0];
    }

    protected String[] getServletMappings() {
        return new String[]{"/"};
    }

}
----

到此一个基本的例子已经完成了，当你访问/index路径的时候，会被拦截要求登录，输入验证后跳转到index页面。

== 基础功能详解

=== 登录配置
在默认的配置中，系统为我们配置了登录页，但是更多情况下，我们想使用自己的登录页，代码如下：
[source,java]
----
protected void configure(HttpSecurity http) throws Exception {
	http
		.authorizeRequests()
			.anyRequest().authenticated()
			.and()
		.formLogin()
			.loginPage("/login")  <1>
			.permitAll();        <2>
}
----

<1> 指定登录页
<2> 允许所有人访问

自定义登录页JSP实现
[source,jsp]
----
<c:url value="/login" var="loginUrl"/>
<form action="${loginUrl}" method="post">       <1>
	<c:if test="${param.error != null}">        <2>
		<p>
			Invalid username and password.
		</p>
	</c:if>
	<c:if test="${param.logout != null}">       <3>
		<p>
			You have been logged out.
		</p>
	</c:if>
	<p>
		<label for="username">Username</label>
		<input type="text" id="username" name="username"/>	<4>
	</p>
	<p>
		<label for="password">Password</label>
		<input type="password" id="password" name="password"/>	<5>
	</p>
	<input type="hidden"                        <6>
		name="${_csrf.parameterName}"
		value="${_csrf.token}"/>
	<button type="submit" class="btn">Log in</button>
</form>
----


<1> POST请求提交到/login认证用户身份（/login是系统默认的认证接口）
<2> 如果请求参数存在error，显示认证失败
<3> 如果请求参数存在logout, 显示登出成功
<4> name必须是username
<5> name必须是password
<6> 防止csrf攻击

=== 登出配置

使用WebSecurityConfigurerAdapter时，会自动应用注销功能。默认情况下访问URL /logout 将通过以下方式注销用户：

* 使HTTP会话无效
* 清理已配置的任何RememberMe认证
* 清除SecurityContextHolder
* 重定向到/login?logout

但是，类似于配置登录功能，您还可以有多种选项来进一步自定义注销要求：

[source,java]
----
protected void configure(HttpSecurity http) throws Exception {
	http
		.logout()                                                                <1>
			.logoutUrl("/my/logout")                                                <2>
			.logoutSuccessUrl("/my/index")                                           <3>
			.logoutSuccessHandler(logoutSuccessHandler)                              <4>
			.invalidateHttpSession(true)                                             <5>
			.addLogoutHandler(logoutHandler)                                         <6>
			.deleteCookies(cookieNamesToClear)                                       <7>
			.and()
		...
}
----

<1> 提供注销支持。这在使用WebSecurityConfigurerAdapter时会自动应用。
<2> 触发注销的URL（默认为/注销）。如果启用CSRF保护（默认），则该请求也必须是POST。有关更多信息，请咨询JavaDoc。
<3> 注销后重定向到的URL。默认是/login?logout。有关更多信息，请咨询JavaDoc。
<4> 让我们来指定一个自定义的LogoutSuccessHandler。如果指定了，logoutSuccessUrl（）将被忽略。有关更多信息，请咨询JavaDoc。
<5> 指定在注销时是否使HttpSession失效。默认是true。配置下面的SecurityContextLogoutHandler。有关更多信息，请咨询JavaDoc。
<6> 添加一个LogoutHandler。 SecurityContextLogoutHandler默认添加为最后一个LogoutHandler。
<7> 允许指定要在注销成功时删除的cookie的名称。这是一个明确添加CookieClearingLogoutHandle的快捷方式。

*LogoutHandler*

通常，LogoutHandler实现指示参与注销处理的类。它们将被调用来执行必要的清理。因此，他们不应该抛出异常。提供了各种实现：

* PersistentTokenBasedRememberMeServices
* TokenBasedRememberMeServices
* CookieClearingLogoutHandler
* CsrfLogoutHandler
* SecurityContextLogoutHandler

NOTE: 框架还提供了addLogoutHandler(logoutHandler) 方法的快捷方式，例如deleteCookies()就是CookieClearingLogoutHandler的快捷方式。

*LogoutSuccessHandler*

LogoutSuccessHandler在LogoutFilter成功注销后被调用，以处理例如重定向或转发到适当的目的地。请注意，该接口与LogoutHandler几乎相同，但可能引发异常。

提供了以下实现：

* SimpleUrlLogoutSuccessHandler
* HttpStatusReturningLogoutSuccessHandler

如上所述，您不需要直接指定SimpleUrlLogoutSuccessHandler。流式API通过设置logoutSuccessUrl（）提供了一个快捷方式。这将在后台设置SimpleUrlLogoutSuccessHandler。提供的URL在注销后重定向。默认是/login?logout。

HttpStatusReturningLogoutSuccessHandler可以在应用在REST API类型场景。LogoutSuccessHandler不是在成功注销后重定向到URL，而是允许您返回纯HTTP状态码。缺省情况下将返回状态代码200。


=== URL认证

我们的示例只需要用户进行身份验证，并已为我们的应用程序中的每个URL完成此操作。我们可以通过向我们的http.authorizeRequests（）方法添加多个子项来为我们的URL指定自定义需求。例如：
[source,java]
----
protected void configure(HttpSecurity http) throws Exception {
	http
		.authorizeRequests()                                                                <1>
			.antMatchers("/resources/**", "/signup", "/about").permitAll()                  <2>
			.antMatchers("/admin/**").hasRole("ADMIN")                                      <3>
			.antMatchers("/db/**").access("hasRole('ADMIN') and hasRole('DBA')")            <4>
			.anyRequest().authenticated()                                                   <5>
			.antMatchers("/db2/**").hasAuthority("USER")                                    <6>
			.and()
		// ...
		.formLogin();
}
----

<1> http.authorizeRequests（）方法可以有多个路径组合，每个匹配者按照他们声明的顺序被执行。
<2> 指定了任何用户都可以访问多个网址的格式。具体来说，如果URL以“/resources/”开头，等于“/ignup”或等于“/ about”，则可以被任何用户访问。
<3> 任何以“/admin/”开头的网址都将限制为被“ROLE_ADMIN”角色的用户访问。你会注意到，因为我们调用hasRole方法，所以我们不需要指定“ROLE_”前缀。
<4> 任何以“/db/”开头的URL都需要用户同时拥有“ROLE_ADMIN”和“ROLE_DBA”。你会注意到，因为我们正在使用hasRole表达式，所以我们不需要指定“ROLE_”前缀。
<5> 任何尚未匹配的URL只需要用户进行身份验证即可访问
<6> 任何以“/db2/”开头的URL都需要用户同时拥有USER权限

NOTE: 在spring security的数据库中，角色是被当成权限来处理的。例如ADMIN角色，对应的权限字符串就是ROLE_ADMIN.给特定的一组人（角色或用户组）赋予特定的一组权限
IMPORTANT: 可以把上面的配置从数据库中加载，实现权限管理。

=== 方法认证

从2.0版本开始，Spring Security已经大大改善了对服务层方法的安全性的支持。它提供了对JSR-250注解和框架原始@Secured的支持。从3.0开始，您还可以使用基于表达式的新注释。您可以将安全应用于单个bean，使用intercept-method元素来装饰bean声明，或者可以使用AspectJ样式切入点在整个服务层中保护多个bean。


==== @Secured

我们可以在任何@Configuration实例上使用@EnableGlobalMethodSecurity注释来启用基于注解的安全性。例如，以下将启用Spring Security的@Secured注释。
[source,java]
----
@EnableGlobalMethodSecurity(securedEnabled = true)
public class MethodSecurityConfig {
// ...
}
----
然后向方法（在类或接口上）添加注解将相应地限制对该方法的访问。 Spring Security的本地注解支持为该方法定义了一组属性。这些将被传递给AccessDecisionManager以供其做出实际决定
[source,java]
----
public interface BankService {

@Secured("IS_AUTHENTICATED_ANONYMOUSLY")
public Account readAccount(Long id);

@Secured("IS_AUTHENTICATED_ANONYMOUSLY")
public Account[] findAccounts();

@Secured("ROLE_TELLER")
public Account post(Account account, double amount);
}
----

==== JSR-250注解

.启动支持
[source,java]
----
@EnableGlobalMethodSecurity(jsr250Enabled = true)
public class MethodSecurityConfig {
// ...
}
----
你可以在方法上添加上面的注解：

* @DenyAll 拒绝所有访问
* @RolesAllowed({"USER", "ADMIN"})  该方法只要具有"USER", "ADMIN"任意一种权限就可以访问。这里可以省略前缀ROLE_，实际的权限可能是ROLE_ADMIN
* @PermitAll 允许所有访问

==== 基于表达式的注解

这些都是基于标准的，允许应用简单的基于角色的约束,基于表达式的注解要强大的多。

.开启支持
[source,java]
----
@EnableGlobalMethodSecurity(prePostEnabled = true)
public class MethodSecurityConfig {
// ...
}
----

*@PreAuthorize*
在方法执行之前，检查是否有权限

.简单使用
[source,java]
----
public interface BankService {

		@PreAuthorize("isAnonymous()")
		public Account readAccount(Long id);

		@PreAuthorize("isAnonymous()")
		public Account[] findAccounts();

		@PreAuthorize("hasAuthority('ROLE_TELLER')")
		public Account post(Account account, double amount);
}

----

.高级使用
[source,java]
----
@PreAuthorize("hasPermission(#contact, 'admin')")
public void deletePermission(Contact contact, Sid recipient, Permission permission);
----
这里我们实际上使用方法参数作为表达式的一部分来决定当前用户是否具有给定联系人的“管理员”权限。在这里我们不仅是对方法有权限，还对特定的数据有权限。

*@PostAuthorize*
通常情况下，您可能希望在调用该方法后执行访问控制检查。 这可以使用@PostAuthorize注释来实现。 要从方法访问返回值，请在表达式中使用内置名称returnObject。 

*@PreFilter和@PostFilter*
正如你可能已经知道的那样，Spring Security支持对集合和数组的过滤，现在可以使用表达式来实现。 这通常是对方法的返回值执行的。 例如：
[source,java]
----
@PreAuthorize("hasRole('USER')")
@PostFilter("hasPermission(filterObject, 'read') or hasPermission(filterObject, 'admin')")
public List<Contact> getAll();
----
Spring Security遍历返回的集合并删除提供的表达式为false的所有元素

[NOTE]
====

@PreAuthorize("#contact.name == authentication.name")在方法上经常被使用，我们可以自定义一个快捷方式的注解

----
@Retention(RetentionPolicy.RUNTIME)
@PreAuthorize("#contact.name == authentication.name")
public @interface ContactPermission {}
----

====

=== ACL认证

Spring Security的域对象实例安全功能以访问控制列表（ACL）的概念为中心，系统中的每个域对象实例都有自己的ACL，ACL记录了谁可以使用该域对象。考虑到这一点，Spring Security为您的应用程序提供了三个与ACL相关的主要功能：

* 检索域对象ACL信息的方法（并修改这些ACL）
* 在调用方法之前，确保给定主体被允许处理域对象
* 在调用方法之后，确保给定主体被允许处理对象（或返回的对象）

==== ACL表信息

* ACL_SID：该表允许我们唯一标识系统中的任何主体或权限。
|===
|列|类型|描述
|ID|BIGINT | 主键列
|SID|VARCHAR(100)| 主体标识或权限标识
|principal|BOOLEAN | true表明SID是主体标识，false权限标识
|===
* ACL_CLASS:唯一标识系统中的域对象。
|===
|列|类型|描述
|ID|BIGINT | 主键列
|class |VARCHAR(100)| 类名称
|===

* ACL_OBJECT_IDENTITY：存储系统中每个唯一域对象实例的信息。
|===
|列|类型|描述
|ID|BIGINT | 主键列
|object_id_class |BIGINT | 外键，关联ACL_CLASS表的ID列
|object_id_identity|VARCHAR(36)|一个唯一的标识符，以便我们知道哪个ACL_CLASS实例
|parent_object|BIGINT|自关联，父对象的ID
|owner_sid|BIGINT|ACL_SID表的外键，代表域对象实例的所有者
|entries_inheriting|BOOLEAN |是否允许从父对象继承

|===

* ACL_ENTRY ：ACL_ENTRY存储分配给用户的权限。

|===
|列|类型|描述
|ID|BIGINT | 主键列
|object_id_identity|BIGINT|关联ACL_OBJECT_IDENTITY表的主键
|ace_order|INTEGER |
|sid |BIGINT|ACL_SID表的外键，代表域对象实例的所有者
|mask |INTEGER |整数位掩码。读取（位0），写入（位1），创建（位2），删除（位3）和管理（位4）权限
|granting  |BOOLEAN |表示实际权限被授予或拒绝
|audit_success |BOOLEAN | 审计成功
|audit_failure  |BOOLEAN | 审计失败
|===

==== 关键接口

* Acl：每个域对象都有且仅有一个Acl对象，它内部持有AccessControlEntry并知道Acl的所有者。 Acl不直接引用域对象，而是引用ObjectIdentity。 Acl存储在ACL_OBJECT_IDENTITY表中。
* AccessControlEntry：一个Acl拥有多个AccessControlEntry，在框架中通常缩写为ACE。 每个ACE引用Permission，Sid和Acl的特定元组。 ACE也可以是授予或不授予，并包含审计设置。 ACE存储在ACL_ENTRY表中。
* Permission：表示特定的不可变位掩码，并为位掩码和输出信息提供便利功能。 上面介绍的基本权限（位0到4）包含在BasePermission类中。
* Sid：ACL模块需要引用主体和GrantedAuthority[]。公共类包括PrincipalSid（用于表示Authentication对象内的主体）和GrantedAuthoritySid。 安全标识信息存储在ACL_SID表中。
* ObjectIdentity：每个域对象都由一个ObjectIdentity在ACL模块内部表示。 默认实现称为ObjectIdentityImpl。
* AclService：检索适给定ObjectIdentity的Acl。 在包含的实现（JdbcAclService）中，检索操作被委托给LookupStrategy。LookupStrategy提供了一种高度优化的策略，用于检索ACL信息，使用批量检索（BasicLookupStrategy）并支持利用实例化视图，分层查询和类似以性能为中心的非ANSI SQL功能的自定义实现。
* MutableAclService：允许修改后的Acl用于持久化。

==== 入门
要开始使用Spring Security的ACL功能，您需要将ACL信息存储在某处。这需要使用Spring来实例化一个DataSource。然后将DataSource注入到JdbcMutableAclService和BasicLookupStrategy实例中。后者提供了高性能的ACL检索功能，前者提供了增强功能。 有关示例配置，请参阅Spring Security附带的示例。 

以下代码片段显示了如何创建Acl或修改现有的Acl：
[source,java]
----
// Prepare the information we'd like in our access control entry (ACE)
ObjectIdentity oi = new ObjectIdentityImpl(Foo.class, new Long(44));
Sid sid = new PrincipalSid("Samantha");
Permission p = BasePermission.ADMINISTRATION;

// Create or update the relevant ACL
MutableAcl acl = null;
try {
acl = (MutableAcl) aclService.readAclById(oi);
} catch (NotFoundException nfe) {
acl = aclService.createAcl(oi);
}

// Now grant some permissions via an access control entry (ACE)
acl.insertAce(acl.getEntries().length, p, sid, true);
aclService.updateAcl(acl);
----

在上面的示例中，我们检索与标识号为44的“Foo”域对象关联的ACL。然后，我们添加一个ACE，以便名为“Samantha”的主体可以“管理”该对象。 
insertAce方法的第一个参数是确定Acl中的哪个位置将插入新条目。 在上面的示例中，我们只是将新ACE放在现有ACE的末尾。 最后一个参数是布尔值，表示ACE是否授予或拒绝。 大多数时候它会授予（true），但如果拒绝（false），则权限将被有效阻止。

